// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4o6eR7RxS5oCeXD3PNif2ycK0BNLCQjk',
    appId: '1:293964114440:web:1951d201c1273d9a19bfbd',
    messagingSenderId: '293964114440',
    projectId: 'petadoption-aad93',
    authDomain: 'petadoption-aad93.firebaseapp.com',
    storageBucket: 'petadoption-aad93.firebasestorage.app',
    measurementId: 'G-HCCMMEVHFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8r2_sVV4q5YMKHQ_iqufVgyksUnKhCjI',
    appId: '1:293964114440:android:9cf031699efd15f419bfbd',
    messagingSenderId: '293964114440',
    projectId: 'petadoption-aad93',
    storageBucket: 'petadoption-aad93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZI-WZvWXp8Prjm3iu4r50topDHfh2HM',
    appId: '1:293964114440:ios:792badf9b28b4fc019bfbd',
    messagingSenderId: '293964114440',
    projectId: 'petadoption-aad93',
    storageBucket: 'petadoption-aad93.firebasestorage.app',
    iosBundleId: 'com.example.petadoption',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZI-WZvWXp8Prjm3iu4r50topDHfh2HM',
    appId: '1:293964114440:ios:792badf9b28b4fc019bfbd',
    messagingSenderId: '293964114440',
    projectId: 'petadoption-aad93',
    storageBucket: 'petadoption-aad93.firebasestorage.app',
    iosBundleId: 'com.example.petadoption',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4o6eR7RxS5oCeXD3PNif2ycK0BNLCQjk',
    appId: '1:293964114440:web:4559f4c6ff7ba8bc19bfbd',
    messagingSenderId: '293964114440',
    projectId: 'petadoption-aad93',
    authDomain: 'petadoption-aad93.firebaseapp.com',
    storageBucket: 'petadoption-aad93.firebasestorage.app',
    measurementId: 'G-HBLX9KS5DZ',
  );
}
